import { createHash } from "node:crypto";
import { XMLParser, XMLValidator } from "fast-xml-parser";
import provinces from "./provinces.json";
export const feeds=[{name:"TRT Haber · Türkiye",url:"https://www.trthaber.com/turkiye_articles.rss",category:"Gündem"},{name:"TRT Haber · Ekonomi",url:"https://www.trthaber.com/ekonomi_articles.rss",category:"Ekonomi"},{name:"TRT Haber · Bilim Teknoloji",url:"https://www.trthaber.com/bilim_teknoloji_articles.rss",category:"Teknoloji"}] as const;
export type Run={id:string;startedAt:string;finishedAt:string|null;status:string;count:number;sources:{name:string;count:number;error?:string}[]};
export type Article={id:string;title:string;summary:string;imageUrl:string|null;url:string;source:string;category:string;publishedAt:string;collectedAt:string;provinceCodes:string[]};
export function fold(v:string){return v.toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ı/g,"i")}
export function matchProvinces(text:string){const n=fold(text);return provinces.filter(p=>new RegExp(`(^|[^a-z])${fold(p.name)}(?=$|[^a-z])`).test(n)).map(p=>p.code)}
function clean(v:unknown){return typeof v==="string"?v.replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim():""}
export function parseFeed(xml:string,feed:typeof feeds[number],now=new Date()):Article[]{if(xml.length>2000000||/<!DOCTYPE|<!ENTITY/i.test(xml)||XMLValidator.validate(xml)!==true)throw Error("Geçersiz RSS yanıtı");const parsed=new XMLParser({ignoreAttributes:false,processEntities:true,attributeNamePrefix:"@"}).parse(xml);if(!parsed.rss?.channel)throw Error("RSS kanalı bulunamadı");const items=parsed.rss.channel.item??[];return(Array.isArray(items)?items:[items]).slice(0,200).flatMap((item):Article[]=>{const title=clean(item.title);const summary=clean(item.description).slice(0,600);const imageValue=item.enclosure?.["@url"]??item["media:content"]?.["@url"]??null;const imageUrl=typeof imageValue==="string"&&imageValue.startsWith("https://")?imageValue:null;let url:URL;try{url=new URL(clean(item.link))}catch{return[]}if(url.protocol!=="https:"||url.hostname!=="www.trthaber.com"||!url.pathname.startsWith("/haber/"))return[];const published=new Date(item.pubDate);if(!title||!Number.isFinite(published.getTime())||published>new Date(now.getTime()+300000))return[];return[{id:createHash("sha256").update(url.href).digest("hex"),title,summary,imageUrl,url:url.href,source:"TRT Haber",category:feed.category,publishedAt:published.toISOString(),collectedAt:now.toISOString(),provinceCodes:matchProvinces(title+" "+summary)}]})}