import { createHash } from "node:crypto";
import { XMLParser, XMLValidator } from "fast-xml-parser";
import provinces from "./provinces.json";
export const feeds=[{name:"TRT Haber · Türkiye",url:"https://www.trthaber.com/turkiye_articles.rss",category:"Gündem"},{name:"TRT Haber · Ekonomi",url:"https://www.trthaber.com/ekonomi_articles.rss",category:"Ekonomi"},{name:"TRT Haber · Bilim Teknoloji",url:"https://www.trthaber.com/bilim_teknoloji_articles.rss",category:"Teknoloji"},{name:"TRT Haber · Yaşam",url:"https://www.trthaber.com/yasam_articles.rss",category:"Yaşam"},{name:"TRT Haber · Eğitim",url:"https://www.trthaber.com/egitim_articles.rss",category:"Eğitim"},{name:"TRT Haber · Sağlık",url:"https://www.trthaber.com/saglik_articles.rss",category:"Sağlık"},{name:"AA · Teyit Hattı",url:"https://www.aa.com.tr/tr/teyithatti/rss/news?cat=0",category:"Teyit"}] as const;
export type Run={id:string;startedAt:string;finishedAt:string|null;status:string;count:number;sources:{name:string;count:number;error?:string}[]};
export type Article={id:string;title:string;summary:string;imageUrl:string|null;url:string;source:string;category:string;publishedAt:string;collectedAt:string;provinceCodes:string[];rights?:{mode:string;owner:string;policyUrl:string;imageAllowed:boolean;checkedAt:string};hidden?:boolean;editedAt?:string};
export function fold(v:string){return v.toLocaleLowerCase("tr-TR").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/ı/g,"i")}
export function matchProvinces(text:string){
 // Proper-name casing avoids matching ordinary words like ağrı, ordu and tokat.
 return provinces.filter(p=>[p.name,p.name.toLocaleUpperCase("tr-TR"),p.name.replace("â","a")].some(name=>new RegExp("(^|[^\\p{L}])"+name+"(?=$|[^\\p{L}])","u").test(text.normalize("NFC")))).map(p=>p.code);
}
function clean(v:unknown){return typeof v==="string"?v.replace(/<[^>]*>/g," ").replace(/\s+/g," ").trim():""}
export function parseFeed(xml:string,feed:typeof feeds[number],now=new Date()):Article[]{if(xml.length>2000000||/<!DOCTYPE|<!ENTITY/i.test(xml)||XMLValidator.validate(xml)!==true)throw Error("Geçersiz RSS yanıtı");const parsed=new XMLParser({ignoreAttributes:false,processEntities:true,attributeNamePrefix:"@"}).parse(xml);if(!parsed.rss?.channel)throw Error("RSS kanalı bulunamadı");const items=parsed.rss.channel.item??[];return(Array.isArray(items)?items:[items]).slice(0,200).flatMap((item):Article[]=>{const title=clean(item.title);const locationText=clean(item.description);const summary="";const imageValue=item.enclosure?.["@url"]??item["media:content"]?.["@url"]??null;const imageUrl=null;void imageValue;let url:URL;try{url=new URL(clean(item.link))}catch{return[]}if(url.protocol!=="https:"||url.hostname!==new URL(feed.url).hostname||url.username!==""||url.password!==""||url.port!==""||!url.pathname.startsWith(feed.name.startsWith("AA")?"/tr/teyithatti/":"/haber/"))return[];const published=new Date(item.pubDate);if(!title||!Number.isFinite(published.getTime())||published>now)return[];return[{id:createHash("sha256").update(url.href).digest("hex"),title,summary,imageUrl,url:url.href,source:feed.name.startsWith("AA")?"Anadolu Ajansı":"TRT Haber",category:feed.category,publishedAt:published.toISOString(),collectedAt:now.toISOString(),provinceCodes:matchProvinces(title+" "+locationText),rights:{mode:"link-index",owner:feed.name.startsWith("AA")?"Anadolu Ajansı":"TRT Haber",policyUrl:feed.name.startsWith("AA")?"https://www.aa.com.tr/tr/teyithatti/p/rss-linkleri":"https://www.trthaber.com/sitene_ekle.html",imageAllowed:false,checkedAt:now.toISOString()}}]})}
