allowBuilds:
  '@embedded-postgres/windows-x64': true
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
overrides:
  find-my-way: ^9.6.1
  postcss: ^8.5.23
  sharp: ^0.35.4
  valibot: ^1.4.2

  fast-uri: ^3.1.6
  nanoid@<3.3.18: ^3.3.18
  deepmerge-ts: ^8.0.2
  mysql2: ^3.23.1
