export type CommerceSource={id:string;name:string;origin:string;trustScore:number;productPatterns:RegExp[];sitemapCandidates?:string[];seedUrls?:string[]};

export const commerceSources:CommerceSource[]=[
  {id:"amazon-tr",name:"Amazon Türkiye",origin:"https://www.amazon.com.tr",trustScore:96,productPatterns:[/\/dp\//i,/\/gp\/product\//i]},
  {id:"trendyol",name:"Trendyol",origin:"https://www.trendyol.com",trustScore:94,productPatterns:[/-p-\d+/i]},
  {id:"hepsiburada",name:"Hepsiburada",origin:"https://www.hepsiburada.com",trustScore:94,productPatterns:[/-p-/i]},
  {id:"n11",name:"n11",origin:"https://www.n11.com",trustScore:90,productPatterns:[/\/urun\//i]},
  {id:"teknosa",name:"Teknosa",origin:"https://www.teknosa.com",trustScore:94,productPatterns:[/-p-\d+/i,/\/urun\//i]},
  {id:"mediamarkt",name:"MediaMarkt Türkiye",origin:"https://www.mediamarkt.com.tr",trustScore:94,productPatterns:[/\/product\//i,/\/tr\/product\//i]},
  {id:"vatan",name:"Vatan Bilgisayar",origin:"https://www.vatanbilgisayar.com",trustScore:93,productPatterns:[/\/[^/]+\.html$/i]},
  {id:"migros",name:"Migros",origin:"https://www.migros.com.tr",trustScore:93,productPatterns:[/-p-/i,/\/urun\//i]},
  {id:"carrefoursa",name:"CarrefourSA",origin:"https://www.carrefoursa.com",trustScore:93,productPatterns:[/\/p\//i,/\/product\//i]},
  {id:"boyner",name:"Boyner",origin:"https://www.boyner.com.tr",trustScore:92,productPatterns:[/-p-/i,/\/urun\//i]},
  {id:"lcw",name:"LC Waikiki",origin:"https://www.lcw.com",trustScore:92,productPatterns:[/\/urun-/i,/\/product-/i]},
  {id:"defacto",name:"DeFacto",origin:"https://www.defacto.com.tr",trustScore:92,productPatterns:[/\/product\//i,/\/urun\//i]},
  {id:"flo",name:"FLO",origin:"https://www.flo.com.tr",trustScore:92,productPatterns:[/-p-/i,/\/urun\//i]},
  {id:"koctas",name:"Koçtaş",origin:"https://www.koctas.com.tr",trustScore:93,productPatterns:[/\/p\//i,/\/urun\//i]},
  {id:"ikea",name:"IKEA Türkiye",origin:"https://www.ikea.com.tr",trustScore:94,productPatterns:[/\/urun\//i,/\/p\//i]},
  {id:"pazarama",name:"Pazarama",origin:"https://www.pazarama.com",trustScore:90,productPatterns:[/\/urun\//i,/-p-/i]},
  {id:"ciceksepeti",name:"ÇiçekSepeti",origin:"https://www.ciceksepeti.com",trustScore:90,productPatterns:[/\/urun\//i,/-p-/i]},
  {id:"a101",name:"A101",origin:"https://www.a101.com.tr",trustScore:92,productPatterns:[/\/market\//i,/\/urun\//i]},
  {id:"sok",name:"ŞOK Market",origin:"https://www.sokmarket.com.tr",trustScore:92,productPatterns:[/\/p\//i,/\/urun\//i]},
  {id:"ebebek",name:"ebebek",origin:"https://www.e-bebek.com",trustScore:92,productPatterns:[/\/p\//i,/\/urun\//i]},
  {id:"gratis",name:"Gratis",origin:"https://www.gratis.com",trustScore:92,productPatterns:[/-p-\d+/i,/\/p\//i,/\/urun\//i],seedUrls:["https://www.gratis.com/elektrikli-urunler/duzlestirici-c-511040101"]},
  {id:"watsons",name:"Watsons Türkiye",origin:"https://www.watsons.com.tr",trustScore:92,productPatterns:[/\/p\//i,/\/urun\//i],seedUrls:["https://www.watsons.com.tr/sac-bakim/c/102"]},
  {id:"mavi",name:"Mavi",origin:"https://www.mavi.com",trustScore:92,productPatterns:[/\/p\//i,/\/urun\//i],seedUrls:["https://www.mavi.com/erkek/tisort/c/2"]},
  {id:"koton",name:"Koton",origin:"https://www.koton.com",trustScore:92,productPatterns:[/\/product\/\d+/i,/-\d{6,}(?:-\d+)?\/?$/i,/\/p\//i,/\/urun\//i],seedUrls:["https://www.koton.com/kadin-elbise/"]},
  {id:"english-home",name:"English Home",origin:"https://www.englishhome.com",trustScore:92,productPatterns:[/\/p\//i,/\/urun\//i]},
  {id:"madame-coco",name:"Madame Coco",origin:"https://www.madamecoco.com",trustScore:92,productPatterns:[/\/p\//i,/\/urun\//i]},
  {id:"vivense",name:"Vivense",origin:"https://www.vivense.com",trustScore:91,productPatterns:[/\/urun\//i,/-p-/i]},
  {id:"evidea",name:"Evidea",origin:"https://www.evidea.com",trustScore:91,productPatterns:[/\/urun\//i,/-p-/i]},
  {id:"avansas",name:"Avansas",origin:"https://www.avansas.com",trustScore:92,productPatterns:[/\/urun\//i,/-p-/i]},
  {id:"dr",name:"D&R",origin:"https://www.dr.com.tr",trustScore:92,productPatterns:[/\/kitap\//i,/\/urun\//i]},
  {id:"idefix",name:"idefix",origin:"https://www.idefix.com",trustScore:91,productPatterns:[/\/urun\//i,/-p-/i]},
  {id:"kitapyurdu",name:"Kitapyurdu",origin:"https://www.kitapyurdu.com",trustScore:91,productPatterns:[/\/kitap\//i,/\/urun\//i]},
  {id:"decathlon",name:"Decathlon Türkiye",origin:"https://www.decathlon.com.tr",trustScore:93,productPatterns:[/\/p\//i,/\/urun\//i]}
];
