"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import type {FinanceSnapshot,Market} from "@/lib/finans-ai";
const categories=["Tümü","Borsa İstanbul","Dövizler","Metaller","Kripto paralar","Emtialar"];
const stamp=(s:string)=>s?(s.includes("T")?new Date(s).toLocaleString("tr-TR",{timeZone:"Europe/Istanbul",dateStyle:"short",timeStyle:"short"}):s):"Veri zamanı yok";
const price=(item:Market)=>item.price===null?"Veri yok":item.price.toLocaleString("tr-TR",{minimumFractionDigits:2,maximumFractionDigits:item.price<1?4:2});
function Trend({values,up}:{values:number[];up:boolean}){if(values.length<2)return <span className="fin-no-trend">Grafik verisi yok</span>;const lo=Math.min(...values),hi=Math.max(...values);const points=values.map((v,i)=>`${i/(values.length-1)*120},${30-(v-lo)/(hi-lo||1)*26}`).join(" ");return <svg className={up?"fin-up":"fin-down"} viewBox="0 0 120 34" role="img" aria-label="Son bir ayın günlük kapanış eğilimi"><polyline points={points} fill="none" stroke="currentColor" strokeWidth="2"/></svg>;}
export function FinanceDashboard(){
 const [data,setData]=useState<FinanceSnapshot|null>(null),[category,setCategory]=useState("Tümü"),[search,setSearch]=useState(""),[busy,setBusy]=useState(true),[error,setError]=useState("");
 useEffect(()=>{const controller=new AbortController();let running=false;async function refresh(){if(running)return;running=true;setBusy(true);try{const r=await fetch("/api/finans-ai",{signal:controller.signal,cache:"no-store"});if(!r.ok)throw Error();const d=await r.json();if(!controller.signal.aborted){setData(d);setError("");}}catch{if(!controller.signal.aborted)setError("Yeni veriye ulaşılamadı. Varsa son alınan değerler gösteriliyor.");}finally{running=false;if(!controller.signal.aborted)setBusy(false);}}void refresh();const timer=setInterval(()=>{if(!document.hidden)void refresh();},300000);const onRefresh=()=>void refresh();window.addEventListener("finans-refresh",onRefresh);return()=>{controller.abort();clearInterval(timer);window.removeEventListener("finans-refresh",onRefresh);};},[]);
 const items=data?.items??[],visible=items.filter(i=>(category==="Tümü"||i.category===category)&&(!search||(i.name+" "+i.id+(i.id==="USD"?" dolar amerikan":i.id==="EUR"?" euro avro":"")).toLocaleLowerCase("tr-TR").includes(search.toLocaleLowerCase("tr-TR"))));
 return <div className="fin-shell"><div className="fin-topline"><Link href="/haber-ai">← HaberAI</Link><span>ÜRETİR / FİNANSAL GÖRÜNÜM</span><span>İSTANBUL · UTC+3</span></div><header className="fin-hero"><div><span className="fin-kicker">FİNANSAI</span><h1>Piyasaların<br/><em>ortak ekranı.</em></h1><p>Paranın, üretimin ve dünyanın ritmi.<br/>Beş piyasayı kaynaklı verilerle birlikte izleyin.</p></div><aside><span className="fin-orbit" aria-hidden="true">₺</span><div><strong>{items.filter(i=>i.price!==null).length.toString().padStart(2,"0")}</strong><span>erişilebilir gösterge</span></div><p>{data?"Son kontrol · "+stamp(data.checkedAt):"Kaynaklar kontrol ediliyor"}</p><button disabled={busy} onClick={()=>window.dispatchEvent(new Event("finans-refresh"))}>{busy?"Veriler alınıyor…":"Verileri yenile ↗"}</button></aside></header>
 <section className="fin-highlights" aria-label="Öne çıkan piyasalar">{["USD","EUR","GRAM","BRENT"].map(id=>{const item=items.find(i=>i.id===id);return <button key={id} onClick={()=>{setCategory(item?.category??"Tümü");setSearch("");document.getElementById("fin-markets")?.scrollIntoView({behavior:"smooth",block:"start"});}}><span>{item?.name??({USD:"USD / TRY",EUR:"EUR / TRY",GRAM:"Gram altın",BRENT:"Brent vadeli"}[id])}</span><strong>{item?price(item):"—"}</strong><small>{item?.unit??"Yükleniyor"} · {item?stamp(item.asOf):"Kaynak bekleniyor"}</small></button>;})}</section>
 <section id="fin-markets" className="fin-markets"><div className="fin-section-head"><div><span className="fin-kicker">PİYASA MASASI</span><h2>Bugünün görünümü</h2></div><label className="fin-search"><span>Varlık ara</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="BIST 100, Bitcoin, dolar…"/></label></div><nav className="fin-tabs" aria-label="Piyasa kategorileri">{categories.map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}<small>{c==="Tümü"?items.length:items.filter(i=>i.category===c).length}</small></button>)}</nav>
 {error&&<p role="alert" className="fin-notice">{error}</p>}
 <div className="fin-table-wrap"><table><thead><tr><th>Varlık / piyasa</th><th>Son değer</th><th>Günlük %</th><th>1 ay</th><th>Veri zamanı / kaynak</th></tr></thead><tbody>{visible.map(i=><tr key={i.id}><td><strong>{i.name}</strong><small>{i.id} · {i.category}</small></td><td><strong>{price(i)}</strong><small>{i.unit}</small></td><td className={i.change===null?"":i.change>=0?"fin-up":"fin-down"}>{i.change===null?"—":(i.change>=0?"+":"")+i.change.toLocaleString("tr-TR",{maximumFractionDigits:2})+"%"}</td><td><Trend values={i.history} up={(i.change??0)>=0}/></td><td><time>{stamp(i.asOf)}</time><a href={i.url} target="_blank" rel="noreferrer">{i.source} ↗</a><small>{i.note}</small></td></tr>)}</tbody></table></div>
 {!visible.length&&<p className="fin-empty" role="status">{busy?"Piyasa kaynakları yükleniyor…":data?"Bu aramada varlık bulunamadı.":"Kaynaklara ulaşılamadı. Yenile düğmesiyle tekrar deneyin."}</p>}
 <footer className="fin-notes"><p><strong>Fiyatın zamanı önemlidir.</strong> Ekran beş dakikada bir kontrol edilir. Hafta sonu ve tatillerde son işlem günü gösterilir. TCMB kurları günlük gösterge satış kurudur; diğer piyasa verileri gecikmeli olabilir.</p><p>Gram altın, ons altın ve USD/TRY ile hesaplanan teorik 24 ayar değerdir. Vadeli emtialarda birimleri kontrol edin. Grafikler son bir ayın günlük kapanışlarını, değişim önceki mevcut günlük kapanışa göre farkı gösterir. Borsa İstanbul listesi seçili endeks ve hisselerden oluşur.</p></footer></section></div>;
}
