"use client";
import {useEffect,useState} from "react";
import provinces from "@/lib/haber-ai/provinces.json";
import type {Article} from "@/lib/haber-ai/model";
type Editable=Article&{hidden?:boolean;editedAt?:string};
export function HaberEditor(){
 const [items,setItems]=useState<Editable[]>([]),[chosen,setChosen]=useState<Editable|null>(null),[query,setQuery]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch("/api/haber-ai?view=editor",{cache:"no-store"});if(!r.ok)throw Error("Haber arşivine ulaşılamadı.");setItems((await r.json()).articles);}
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 async function save(){if(!chosen)return;setBusy(true);try{const r=await fetch("/api/haber-ai",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:chosen.id,title:chosen.title,summary:chosen.summary??"",provinceCodes:chosen.provinceCodes,hidden:chosen.hidden??false,editedAt:chosen.editedAt??null})});const d=await r.json();if(!r.ok)throw Error(d.error);setChosen({...chosen,editedAt:d.editedAt});await load();setMessage("Kaydedildi. Haritadaki haber güncellendi; ajan bu düzenlemeyi korur.");}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="editor-content"><h2>HaberAI · Harita haberleri</h2><p>Kaynak akışını düzenleyin, şehir eşleşmelerini düzeltin veya haberi haritadan gizleyin.</p><button disabled={busy} onClick={async()=>{setBusy(true);try{const r=await fetch("/api/haber-ai",{method:"POST"});const d=await r.json();if(!r.ok)throw Error(d.error);await load();setMessage("Tarama: "+d.status);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}}>Kaynakları şimdi tara</button><p role="status">{message}</p><label className="editor-field"><span>Arşivde ara</span><input value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="haber-editor-layout"><div className="haber-editor-list">{items.filter(a=>a.title.toLocaleLowerCase("tr-TR").includes(query.toLocaleLowerCase("tr-TR"))).map(a=><button key={a.id} onClick={()=>setChosen({...a})}>{a.hidden?"GİZLİ · ":""}{a.title}</button>)}</div>{chosen&&<div><label className="editor-field"><span>Başlık</span><input value={chosen.title} maxLength={300} onChange={e=>setChosen({...chosen,title:e.target.value})}/></label><label className="editor-field"><span>Özet</span><textarea rows={5} value={chosen.summary??""} maxLength={1000} onChange={e=>setChosen({...chosen,summary:e.target.value})}/></label><fieldset><legend>Haberde geçen şehirler</legend><div className="haber-city-checks">{provinces.map(p=><label key={p.code}><input type="checkbox" checked={chosen.provinceCodes.includes(p.code)} onChange={e=>setChosen({...chosen,provinceCodes:e.target.checked?[...chosen.provinceCodes,p.code]:chosen.provinceCodes.filter(c=>c!==p.code)})}/>{p.name}</label>)}</div></fieldset><label><input type="checkbox" checked={chosen.hidden??false} onChange={e=>setChosen({...chosen,hidden:e.target.checked})}/> Haritada gösterme</label><p><a href={chosen.url} target="_blank" rel="noreferrer">Özgün kaynağı incele ↗</a></p><button className="editor-primary" disabled={busy} onClick={save}>Haberi kaydet ve haritayı güncelle</button></div>}</div></section>;
}
