"use client";
import Link from "next/link";
import {ChevronDown,Menu,Search,X,ArrowUpRight} from "lucide-react";
import {usePathname} from "next/navigation";
import {useEffect,useRef,useState} from "react";
import {ThemeToggle} from "./theme-toggle";
import {siteNavigation} from "@/lib/site-navigation";
export function Header(){
 const pathname=usePathname(),ref=useRef<HTMLElement>(null);const[open,setOpen]=useState(false);const english=pathname.startsWith("/en");
 const close=()=>{ref.current?.querySelectorAll("details[open]").forEach(d=>d.removeAttribute("open"));setOpen(false);};
 useEffect(()=>{const outside=(e:PointerEvent)=>{if(!ref.current?.contains(e.target as Node)){ref.current?.querySelectorAll("details[open]").forEach(d=>d.removeAttribute("open"));setOpen(false);}};const escape=(e:KeyboardEvent)=>{if(e.key!=="Escape")return;const expanded=ref.current?.querySelector("details[open]");if(expanded){expanded.removeAttribute("open");expanded.querySelector("summary")?.focus();}else {setOpen(false);ref.current?.querySelector<HTMLButtonElement>(".nav-mobile-toggle")?.focus();}};document.addEventListener("pointerdown",outside);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("pointerdown",outside);document.removeEventListener("keydown",escape);};},[]);
 return <><header ref={ref} className="site-header sticky top-0 z-50"><div className="section-wrap nav-frame"><Link href={english?"/en":"/"} className="nav-brand" aria-label={english?"Uretir home":"Üretir ana sayfa"} onClick={close}><span className="font-display">üretir<span className="nav-dot">.</span></span><span className="nav-motto">{english?<>Ideas made in Türkiye.<br/>Türkiye üretir.</>:<>Türkiye üretir,<br/>gençler yetişir.</>}</span></Link>
 <nav className={"nav-categories"+(open?" is-open":"")} aria-label="Ana navigasyon" id="site-navigation">{siteNavigation.map((group,index)=>{const active=pathname===group.href||group.items.some(i=>pathname===i.href||pathname.startsWith(i.href+"/"));return <details className={"nav-category"+(index===2?" nav-wide":"")} key={group.href} onToggle={e=>{if(e.currentTarget.open){const current=e.currentTarget;ref.current?.querySelectorAll("details[open]").forEach(d=>{if(d!==current)d.removeAttribute("open");});}}}><summary className="nav-category-trigger" data-active={active}>{group.label}<ChevronDown size={13} aria-hidden="true"/></summary><div className="nav-dropdown"><div className="nav-dropdown-intro"><span>{group.label}</span><p>{group.description}</p></div><div className="nav-dropdown-links">{group.items.map(item=><Link key={item.href} href={item.href} onClick={close} aria-current={pathname===item.href?"page":undefined}>{item.label}<ArrowUpRight size={13} aria-hidden="true"/></Link>)}</div><Link className="nav-category-all" href={group.href} onClick={close}>Tüm {group.label.toLocaleLowerCase("tr-TR")} <span>→</span></Link></div></details>;})}<Link className="nav-mobile-member" href="/uretir-id" onClick={close}>Üretir ID · Çalışma alanı →</Link></nav>
 <div className="nav-actions">{<Link href="/uretir-id" className="nav-id" onClick={close}>Üretir ID</Link>}<Link href="/ara" aria-label="Üretir içinde ara" className="header-search focus-ring" onClick={close}><Search size={15}/><span className="nav-search-text">Ara</span></Link><ThemeToggle/><button className="nav-mobile-toggle focus-ring" aria-label={open?"Menüyü kapat":"Menüyü aç"} aria-expanded={open} aria-controls="site-navigation" onClick={()=>setOpen(!open)}>{open?<X size={20}/>:<Menu size={20}/>}</button></div></div></header><nav className="mobile-app-nav" aria-label={english?"Quick navigation":"Hızlı navigasyon"}><Link href={english?"/en/gelismeler":"/gelismeler"}>◉<span>{english?"Updates":"Gelişmeler"}</span></Link><Link href={english?"/en/harita":"/harita"}>⌖<span>{english?"Map":"Harita"}</span></Link><Link href={english?"/en":"/"}>ü<span>{english?"Home":"Ana sayfa"}</span></Link><Link href={english?"/en/araclar":"/araclar"}>✦<span>{english?"Tools":"Araçlar"}</span></Link><Link href="/uretir-id">◎<span>Üretir ID</span></Link></nav></>;
}
