"use client";
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {LocationPicker} from "./listing-map";
import type {MarketplaceKind} from "@/lib/marketplace/types";
type Mine={id:string;kind:MarketplaceKind;title:string;status:string;version:number;review_note:string;updated_at:string};
type SessionResponse={user:{id:string;handle:string;display_name:string}|null;items?:Mine[];error?:string};
type SaveResponse={ok?:boolean;flags?:string[];reference?:number|null;anomaly?:number|null;error?:string};
type FormState={title:string;description:string;price:string;city:string;district:string;neighborhood:string;sellerRole:string;contactMode:string;listingType:string;propertyType:string;rooms:string;grossM2:string;netM2:string;brand:string;model:string;trim:string;modelYear:string;mileage:string;fuel:string;transmission:string};
const statusLabel:Record<string,string>={draft:"Taslak",pending:"İncelemede",published:"Yayında",rejected:"Düzenleme gerekli",expired:"Süresi doldu"};
async function call(body:unknown):Promise<SaveResponse>{const r=await fetch("/api/marketplace",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json() as SaveResponse;if(!r.ok)throw Error(d.error||"İşlem tamamlanamadı.");return d;}
async function compress(file:File){if(!file.type.startsWith("image/"))throw Error("Yalnızca fotoğraf yükleyin.");const bmp=await createImageBitmap(file),scale=Math.min(1,1100/Math.max(bmp.width,bmp.height)),w=Math.max(1,Math.round(bmp.width*scale)),h=Math.max(1,Math.round(bmp.height*scale)),canvas=document.createElement("canvas");canvas.width=w;canvas.height=h;canvas.getContext("2d")!.drawImage(bmp,0,0,w,h);const blob=await new Promise<Blob|null>(r=>canvas.toBlob(r,"image/webp",.72));bmp.close();if(!blob)throw Error("Fotoğraf işlenemedi.");if(blob.size>330_000)throw Error("Fotoğraf sıkıştırıldıktan sonra hâlâ çok büyük.");return await new Promise<string>((resolve,reject)=>{const fr=new FileReader();fr.onload=()=>resolve(String(fr.result));fr.onerror=()=>reject(Error("Fotoğraf okunamadı."));fr.readAsDataURL(blob);});}
export function ListingComposer({kind}:{kind:MarketplaceKind}){
 const[user,setUser]=useState<SessionResponse["user"]|undefined>(undefined),[mine,setMine]=useState<Mine[]>([]),[open,setOpen]=useState(false),[step,setStep]=useState(1),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[images,setImages]=useState<string[]>([]),[verify,setVerify]=useState<string|null>(null),[loc,setLoc]=useState<{lat:number;lng:number}|null>(null);
 const[form,setForm]=useState<FormState>({title:"",description:"",price:"",city:"",district:"",neighborhood:"",sellerRole:"owner",contactMode:"secure_request",listingType:"Satılık",propertyType:"Konut",rooms:"",grossM2:"",netM2:"",brand:"",model:"",trim:"",modelYear:String(new Date().getFullYear()),mileage:"",fuel:"Benzin",transmission:"Otomatik"});
 const load=useCallback(async()=>{const r=await fetch("/api/marketplace",{cache:"no-store"}),d=await r.json() as SessionResponse;if(!r.ok)throw Error(d.error||"İlan çalışma alanı yüklenemedi.");setUser(d.user);setMine((d.items??[]).filter(x=>x.kind===kind));},[kind]);
 useEffect(()=>{void load().catch(e=>setMsg((e as Error).message));},[load]);
 const set=(k:keyof FormState,v:string)=>setForm(p=>({...p,[k]:v}));
 async function files(list:FileList|null,verification=false){if(!list?.length)return;setBusy(true);setMsg("");try{if(verification){setVerify(await compress(list[0]));}else{const next=[...images];for(const f of Array.from(list).slice(0,3-images.length))next.push(await compress(f));setImages(next.slice(0,3));}}catch(e){setMsg((e as Error).message);}finally{setBusy(false);}}
 async function save(submit:boolean){if(!loc){setMsg("Haritada konumu seçin.");setStep(2);return;}setBusy(true);setMsg("");try{const attributes=kind==="property"?{listingType:form.listingType,propertyType:form.propertyType,rooms:form.rooms,grossM2:Number(form.grossM2),netM2:form.netM2?Number(form.netM2):null}:{brand:form.brand,model:form.model,trim:form.trim,modelYear:Number(form.modelYear),mileage:Number(form.mileage),fuel:form.fuel,transmission:form.transmission};const d=await call({action:"save",kind,submit,title:form.title,description:form.description,price:Number(form.price),city:form.city,district:form.district,neighborhood:form.neighborhood,latitude:loc.lat,longitude:loc.lng,sellerRole:form.sellerRole,contactMode:form.contactMode,images,verificationImage:verify,attributes});setMsg(submit?(d.flags?.length?"İlan incelemeye gönderildi. Sistem bazı noktaları editöre işaretledi.":"İlan incelemeye gönderildi."):"Taslak kaydedildi.");await load();if(submit)setOpen(false);}catch(e){setMsg((e as Error).message);}finally{setBusy(false);}}
 if(user===undefined)return null;
 if(!user)return <div className="market-sell-cta"><div><strong>İlan vermek 3 kısa adım.</strong><span>Üretir ID hesabı, harita konumu ve en az iki fotoğraf yeterli.</span></div><Link href="/uretir-id">Üretir ID ile giriş yap →</Link></div>;
 return <section className="market-compose"><div className="market-compose-head"><div><span className="rule-label">ÜRETİR İLAN</span><h2>{kind==="property"?"Ev / arsa ilanı ver":"Araç ilanı ver"}</h2><p>Telefonunu herkese açmadan güvenli iletişim isteği al. İlanlar yayından önce kontrol edilir.</p></div><button className="market-primary" onClick={()=>setOpen(!open)}>{open?"Kapat":"+ İlan ver"}</button></div>
 {msg&&<p className="market-message" role="status">{msg}</p>}
 {open&&<div className="market-compose-panel"><nav className="market-steps"><button aria-current={step===1} onClick={()=>setStep(1)}>1 · Bilgi</button><button aria-current={step===2} onClick={()=>setStep(2)}>2 · Konum</button><button aria-current={step===3} onClick={()=>setStep(3)}>3 · Fotoğraf</button></nav>
 {step===1&&<div className="market-form-grid"><label><span>İlan başlığı</span><input value={form.title} onChange={e=>set("title",e.target.value)} maxLength={120}/></label><label><span>Fiyat (TL)</span><input type="number" min="1" value={form.price} onChange={e=>set("price",e.target.value)}/></label><label><span>İl</span><input value={form.city} onChange={e=>set("city",e.target.value)}/></label><label><span>İlçe</span><input value={form.district} onChange={e=>set("district",e.target.value)}/></label><label><span>Mahalle</span><input value={form.neighborhood} onChange={e=>set("neighborhood",e.target.value)}/></label><label><span>İlan veren</span><select value={form.sellerRole} onChange={e=>set("sellerRole",e.target.value)}><option value="owner">Sahibi</option><option value="dealer">Galeri / işletme</option><option value="agent">Yetkili danışman</option></select></label>
 {kind==="property"?<><label><span>Tür</span><select value={form.listingType} onChange={e=>set("listingType",e.target.value)}><option>Satılık</option><option>Kiralık</option></select></label><label><span>Gayrimenkul</span><select value={form.propertyType} onChange={e=>set("propertyType",e.target.value)}><option>Konut</option><option>Arsa</option><option>İş yeri</option></select></label><label><span>Oda</span><input value={form.rooms} onChange={e=>set("rooms",e.target.value)} placeholder="3+1"/></label><label><span>Brüt m²</span><input type="number" value={form.grossM2} onChange={e=>set("grossM2",e.target.value)}/></label></>:<><label><span>Marka</span><input value={form.brand} onChange={e=>set("brand",e.target.value)}/></label><label><span>Model</span><input value={form.model} onChange={e=>set("model",e.target.value)}/></label><label><span>Yıl</span><input type="number" value={form.modelYear} onChange={e=>set("modelYear",e.target.value)}/></label><label><span>KM</span><input type="number" value={form.mileage} onChange={e=>set("mileage",e.target.value)}/></label><label><span>Yakıt</span><input value={form.fuel} onChange={e=>set("fuel",e.target.value)}/></label><label><span>Vites</span><input value={form.transmission} onChange={e=>set("transmission",e.target.value)}/></label></>}<label className="market-wide"><span>Açıklama</span><textarea rows={5} value={form.description} onChange={e=>set("description",e.target.value)} maxLength={4000}/><small>Kapora veya ödeme talebini ilanda istemeyin. Alıcıyla güvenli iletişim isteği üzerinden konuşun.</small></label><div className="market-wide market-next"><button className="market-primary" onClick={()=>setStep(2)}>Konumu seç →</button></div></div>}
 {step===2&&<div><p className="market-help">İlanın gerçek konumunu haritada tıkla. Alıcı haritada bu noktayı görecek.</p><LocationPicker value={loc} onChange={setLoc}/><div className="market-next"><button onClick={()=>setStep(1)}>← Geri</button><button className="market-primary" disabled={!loc} onClick={()=>setStep(3)}>Fotoğraflara geç →</button></div></div>}
 {step===3&&<div><div className="market-photo-grid">{images.map((src,i)=><div key={i}><img src={src} alt="İlan fotoğrafı"/><button onClick={()=>setImages(images.filter((_,x)=>x!==i))}>Kaldır</button></div>)}{images.length<3&&<label className="market-upload">+ Fotoğraf ekle<input type="file" accept="image/*" multiple onChange={e=>void files(e.target.files)}/></label>}</div><p className="market-help">Yayın için en az 2 fotoğraf. Fotoğraflar tarayıcıda küçültülür.</p><label className="market-private-photo"><span>Özel kontrol fotoğrafı (isteğe bağlı)</span><small>Yayımlanmaz. Moderasyonun ilanın gerçekten sende olduğunu değerlendirmesine yardımcı olur.</small><input type="file" accept="image/*" onChange={e=>void files(e.target.files,true)}/>{verify&&<b>Kontrol fotoğrafı hazır ✓</b>}</label><div className="market-next"><button onClick={()=>setStep(2)}>← Geri</button><button disabled={busy} onClick={()=>void save(false)}>Taslak kaydet</button><button className="market-primary" disabled={busy||images.length<2} onClick={()=>void save(true)}>{busy?"Gönderiliyor…":"İncelemeye gönder →"}</button></div></div>}</div>}
 {mine.length>0&&<div className="market-mine"><h3>İlanlarım</h3>{mine.map(x=><div key={x.id}><span>{x.title}</span><b>{statusLabel[x.status]??x.status}</b>{x.review_note&&<small>{x.review_note}</small>}{x.status==="published"&&<button onClick={async()=>{try{await call({action:"renew",id:x.id});setMsg("İlan 30 gün daha doğrulandı.");await load();}catch(e){setMsg((e as Error).message);}}}>30 gün yenile</button>}</div>)}</div>}
 </section>;
}
