"use client";
import {useState} from "react";
import Link from "next/link";
type Kind="property"|"vehicle";
async function post(body:unknown){const r=await fetch("/api/marketplace",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Object.assign(new Error(d.error||"İşlem tamamlanamadı."),{status:r.status});return d;}
export function ListingDealRoom({listingId,kind,askingPrice}:{listingId:string;kind:Kind;askingPrice:number}){
 const[mode,setMode]=useState<"offer"|"schedule">("offer"),[amount,setAmount]=useState(String(Math.round(askingPrice*.95))),[date,setDate]=useState(""),[message,setMessage]=useState(""),[status,setStatus]=useState(""),[busy,setBusy]=useState(false),[login,setLogin]=useState(false);
 async function send(){setBusy(true);setStatus("");setLogin(false);try{await post({action:"dealRequest",listingId,kind:mode==="offer"?"offer":kind==="vehicle"?"inspection":"visit",amount:mode==="offer"?Number(amount):null,preferredAt:mode==="schedule"&&date?new Date(date).toISOString():null,message});setStatus(mode==="offer"?"Teklif satıcıya iletildi. 72 saat açık kalacak.":"Randevu isteği satıcıya iletildi.");}catch(e){const x=e as Error&{status?:number};if(x.status===401)setLogin(true);setStatus(x.message);}finally{setBusy(false);}}
 return <section className="deal-room"><div className="deal-room-head"><span className="rule-label">GÜVENLİ İŞLEM ODASI</span><h3>İlanı konuşmaktan işleme taşı.</h3><p>Kapora yok. Önce teklif veya randevu, sonra belge/ekspertiz kontrolü.</p></div><div className="deal-tabs"><button aria-current={mode==="offer"} onClick={()=>setMode("offer")}>Teklif ver</button><button aria-current={mode==="schedule"} onClick={()=>setMode("schedule")}>{kind==="vehicle"?"Ekspertiz planla":"Görüşme planla"}</button></div>{mode==="offer"?<label><span>Teklifin</span><input type="number" min="1" value={amount} onChange={e=>setAmount(e.target.value)}/><small>İlan fiyatı: {new Intl.NumberFormat("tr-TR").format(askingPrice)} TL</small></label>:<label><span>Tarih / saat</span><input type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/></label>}<label><span>Not</span><textarea rows={3} maxLength={700} value={message} onChange={e=>setMessage(e.target.value)} placeholder={kind==="vehicle"?"Ekspertiz yeri/uygun saat notu":"Görüşme için kısa not"}/></label><button className="market-primary" disabled={busy||(mode==="offer"?!Number(amount):!date)} onClick={()=>void send()}>{busy?"Gönderiliyor…":mode==="offer"?"Teklifi gönder →":"Randevu iste →"}</button>{status&&<p role="status">{status}</p>}{login&&<Link href="/uretir-id">Üretir ID ile giriş yap →</Link>}<small className="deal-note">Üretir ödeme/emanet para hizmeti değildir. Resmî belge ve fiziksel kontrol tamamlanmadan ödeme yapmayın.</small></section>;
}
