"use client";
import {useCallback,useEffect,useState} from "react";
type ReviewItem={id:string;kind:"property"|"vehicle";title:string;description:string;status:string;handle:string;display_name:string;city:string;district:string;price:string|number;price_anomaly_pct:string|number|null;moderation_flags:unknown;report_count:number;version:number;images:unknown;verification_image:string|null};
const images=(value:unknown)=>Array.isArray(value)?value.filter((x):x is string=>typeof x==="string"):[];
type ReviewResponse={items?:ReviewItem[];error?:string};
async function call(body?:unknown):Promise<ReviewResponse>{const r=await fetch("/api/marketplace"+(body?"":"?view=review"),body?{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}:{cache:"no-store"});const d=await r.json() as ReviewResponse;if(!r.ok)throw Error(d.error||"İşlem tamamlanamadı.");return d;}
export function MarketplaceReview(){
 const[items,setItems]=useState<ReviewItem[]>([]),[msg,setMsg]=useState("");
 const load=useCallback(async()=>{try{setItems((await call()).items??[]);}catch(e){setMsg((e as Error).message);}},[]);
 useEffect(()=>{void load();},[load]);
 async function review(item:ReviewItem,decision:"published"|"rejected"){const note=decision==="rejected"?(window.prompt("Düzenleme notu")??""):"";try{await call({action:"review",id:item.id,version:item.version,decision,note});setMsg(decision==="published"?"İlan yayımlandı.":"İlan düzenleme için geri gönderildi.");await load();}catch(e){setMsg((e as Error).message);}}
 return <div className="market-review">{msg&&<p>{msg}</p>}{items.map(x=><article key={x.id}><div><b>{x.kind==="vehicle"?"Araç":"Emlak"} · {x.title}</b><span>{x.status} · @{x.handle}</span></div><p>{x.city} / {x.district} · {Number(x.price).toLocaleString("tr-TR")} TL · {x.display_name}</p><div className="market-review-images">{images(x.images).map((src,i)=><img key={i} src={src} alt={"İlan fotoğrafı "+(i+1)}/>)}{x.verification_image&&<figure><img src={x.verification_image} alt="Özel kontrol fotoğrafı"/><figcaption>Yalnız moderasyon · kontrol fotoğrafı</figcaption></figure>}</div><p className="market-review-description">{x.description}</p><small>Fiyat sapması: {x.price_anomaly_pct===null?"referans yok":Number(x.price_anomaly_pct).toFixed(1)+"%"} · Bayraklar: {Array.isArray(x.moderation_flags)?x.moderation_flags.join(", ")||"yok":"yok"} · Rapor: {x.report_count}</small>{x.status==="pending"&&<div><button onClick={()=>void review(x,"rejected")}>Geri gönder</button><button className="editor-primary" onClick={()=>void review(x,"published")}>Yayınla</button></div>}</article>)}</div>;
}
