"use client";
import {useCallback,useEffect,useState} from "react";
type Deal={id:string;listing_id:string;buyer_user_id:string;seller_user_id:string;kind:"offer"|"visit"|"inspection";amount:string|number|null;preferred_at:string|null;message:string;status:"pending"|"accepted"|"declined"|"countered"|"withdrawn";counter_amount:string|number|null;seller_reply:string;expires_at:string;title:string;price:string|number;buyer_handle:string;seller_handle:string};
type Payload={user:{id:string}|null;deals?:Deal[];error?:string};
async function action(body:unknown){const r=await fetch("/api/marketplace",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||"İşlem tamamlanamadı.");return d;}
const money=(n:string|number|null)=>n===null?"—":new Intl.NumberFormat("tr-TR",{maximumFractionDigits:0}).format(Number(n))+" TL";
export function MarketplaceDealInbox(){
 const[user,setUser]=useState<Payload["user"]|undefined>(undefined),[deals,setDeals]=useState<Deal[]>([]),[msg,setMsg]=useState("");
 const load=useCallback(async()=>{const r=await fetch("/api/marketplace",{cache:"no-store"}),d=await r.json() as Payload;if(!r.ok)throw Error(d.error||"İşlem kutusu yüklenemedi.");setUser(d.user);setDeals(d.deals??[]);},[]);
 useEffect(()=>{void load().catch(e=>setMsg((e as Error).message));},[load]);
 async function decide(d:Deal,decision:"accepted"|"declined"|"countered"){const counter=decision==="countered"?Number(window.prompt("Karşı teklif (TL)",String(d.amount??d.price))):null;if(decision==="countered"&&(!counter||counter<=0))return;const reply=window.prompt("Kısa not","")??"";try{await action({action:"dealDecision",id:d.id,decision,counterAmount:counter,reply});setMsg("İşlem isteği güncellendi.");await load();}catch(e){setMsg((e as Error).message);}}
 if(user===undefined||!user)return null;
 const active=deals.filter(d=>d.status!=="withdrawn");
 if(!active.length)return null;
 return <section className="deal-inbox"><div><span className="rule-label">İŞLEM KUTUSU</span><h2>Teklif ve randevular</h2><p>İletişimi ilandan gerçek işleme taşıyan kayıtlı akış.</p></div>{msg&&<p className="market-message">{msg}</p>}<div className="deal-inbox-list">{active.map(d=>{const incoming=d.seller_user_id===user.id;return <article key={d.id}><header><div><strong>{d.title}</strong><span>{d.kind==="offer"?"Teklif":d.kind==="inspection"?"Ekspertiz":"Görüşme"} · {incoming?"@"+d.buyer_handle:"@"+d.seller_handle}</span></div><b data-status={d.status}>{d.status==="pending"?"Bekliyor":d.status==="accepted"?"Kabul":d.status==="declined"?"Reddedildi":d.status==="countered"?"Karşı teklif":"Kapandı"}</b></header><div className="deal-values">{d.kind==="offer"?<><span>İlan {money(d.price)}</span><strong>{money(d.amount)}</strong>{d.counter_amount&&<span>Karşı teklif {money(d.counter_amount)}</span>}</>:<><span>{d.preferred_at?new Date(d.preferred_at).toLocaleString("tr-TR"):"Tarih yok"}</span></>}</div>{d.message&&<p>{d.message}</p>}{d.seller_reply&&<blockquote>{d.seller_reply}</blockquote>}{incoming&&["pending","countered"].includes(d.status)&&<footer><button onClick={()=>void decide(d,"declined")}>Reddet</button>{d.kind==="offer"&&<button onClick={()=>void decide(d,"countered")}>Karşı teklif</button>}<button className="market-primary" onClick={()=>void decide(d,"accepted")}>Kabul et</button></footer>}</article>})}</div></section>;
}
