"use client";
import {useMemo,useState} from "react";
import Link from "next/link";
import {ListingMap} from "./listing-map";
import {ListingComposer} from "./listing-composer";
import {FavoriteButton} from "./favorite-button";
import type {MarketplaceDashboard,MarketplaceListing} from "@/lib/marketplace/types";
const money=(n:number|null)=>n===null?"—":new Intl.NumberFormat("tr-TR",{style:"currency",currency:"TRY",maximumFractionDigits:0}).format(n);
export function MarketplaceHub({data}:{data:MarketplaceDashboard}){
 const[search,setSearch]=useState(""),[city,setCity]=useState(""),[max,setMax]=useState(""),[onlyTrusted,setOnlyTrusted]=useState(false),[refLimit,setRefLimit]=useState(16);
 const cities=[...new Set(data.listings.map(x=>x.city).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"tr"));
 const visible=useMemo(()=>{const q=search.trim().toLocaleLowerCase("tr-TR"),m=max?Number(max):null;return data.listings.filter(x=>(!city||x.city===city)&&(!m||x.price<=m)&&(!q||[x.title,x.city,x.district,...Object.values(x.attributes).map(String)].join(" ").toLocaleLowerCase("tr-TR").includes(q))&&(!onlyTrusted||x.trustBadges.some(b=>b.tone==="good")&&!x.trustBadges.some(b=>b.tone==="warn")));},[data.listings,search,city,max,onlyTrusted]);
 return <main className="market-shell section-wrap"><header className="market-hero"><div><span className="rule-label">{data.kind==="property"?"EVAI / HARİTALI İLAN":"ARABAAI / HARİTALI İLAN"}</span><h1>{data.kind==="property"?"Evi haritada gör.\nVeriyi yanında tut.":"Aracı haritada gör.\nFiyatı referansla kıyasla."}</h1><p>{data.kind==="property"?"Kaynaklı ilanlar, kullanıcı ilanları ve yerel m² referansı tek yerde.":"İkinci el ilan fiyatını resmî sıfır araç fiyatı ve Üretir'deki benzer ikinci el ilanlarla birlikte gör."}</p></div><div className="market-trust-promise"><strong>Güven, rozet değil kanıt.</strong><p>İlanın kimden geldiğini, ne zaman kontrol edildiğini ve fiyatın referanslardan ne kadar saptığını açıkça gösteriyoruz.</p></div></header>
 <div className="market-stats">{data.stats.map(s=><div key={s.label}><strong>{s.value.toLocaleString("tr-TR")}</strong><span>{s.label}</span></div>)}</div>
 <ListingComposer kind={data.kind}/>
 <section className="market-browser"><div className="market-toolbar"><label><span>Ara</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={data.kind==="property"?"İlçe, oda, ilan…":"Marka, model, şehir…"}/></label><label><span>Şehir</span><select value={city} onChange={e=>setCity(e.target.value)}><option value="">Tümü</option>{cities.map(c=><option key={c}>{c}</option>)}</select></label><label><span>En yüksek fiyat</span><input type="number" min="0" value={max} onChange={e=>setMax(e.target.value)} placeholder="Sınır yok"/></label><label className="market-check"><input type="checkbox" checked={onlyTrusted} onChange={e=>setOnlyTrusted(e.target.checked)}/> Uyarısız ilanlar</label></div><div className="market-count"><b>{visible.length}</b> sonuç · harita ve tablo aynı filtreyi kullanıyor</div>
 <ListingMap items={visible}/>
 <div className="market-table-wrap"><table className="market-table"><thead><tr><th>İlan</th><th>Konum</th><th>Fiyat</th>{data.kind==="vehicle"&&<><th>Sıfır fiyat</th><th>2. el ort.</th></>}<th>Referans</th><th>Güven</th><th>Güncelleme</th><th></th></tr></thead><tbody>{visible.map(item=><MarketRow key={item.id} item={item}/>)}</tbody></table></div>
 {visible.length===0&&<div className="market-empty">Bu filtrelerle ilan yok. Filtreleri genişlet veya ilk ilanı sen ekle.</div>}</section>
 {data.kind==="vehicle"&&<section className="market-reference"><div><span className="rule-label">SIFIR ARAÇ REFERANSI</span><h2>Resmî fiyatı yanında tut.</h2><p>İkinci el ilana bakarken aynı modelin güncel resmî fiyatını ayrı sekmede aramana gerek kalmasın.</p></div><div className="market-ref-grid">{data.references.slice(0,refLimit).map(r=><article key={r.label}><span>{r.label}</span><strong>{money(r.value)}</strong><small>{r.detail}</small></article>)}</div>{data.references.length>refLimit&&<button className="market-more" onClick={()=>setRefLimit(refLimit+24)}>Daha fazla sıfır araç fiyatı göster</button>}</section>}
 <aside className="market-safety"><strong>Alıcı için güvenli işlem kuralı</strong><p>Üretir bir ödeme veya emanet para hizmeti değildir. İlan doğrulama rozetleri mülkiyet garantisi değildir. Aracı/taşınmazı görmeden, resmi belgeleri kontrol etmeden ve karşı tarafı doğrulamadan kapora veya ödeme yapmayın.</p></aside></main>;
}
function MarketRow({item}:{item:MarketplaceListing}){const ref=item.priceReference,delta=ref?((item.price/ref-1)*100):null;return <tr><td><div className="market-title-cell">{item.images[0]?<img src={item.images[0]} alt=""/>:<span className="market-no-image">Görsel yok</span>}<div><strong>{item.title}</strong><small>{item.sourceType==="member"?item.sellerName:item.sourceName}</small>{item.detailUrl?<Link href={item.detailUrl}>İlanı aç →</Link>:item.sourceUrl?<a href={item.sourceUrl} target="_blank" rel="noopener noreferrer">Kaynak ↗</a>:null}</div></div></td><td>{item.city}<small>{item.district}{item.locationPrecision==="approximate"?" · yaklaşık":""}</small></td><td><b>{money(item.price)}</b></td>{item.kind==="vehicle"&&<><td>{money(item.newPrice??null)}</td><td>{item.usedSample&&item.usedSample>=2?money(item.usedAverage??null):"Örnek bekleniyor"}<small>{item.usedSample?item.usedSample+" ilan":""}</small></td></>}<td>{ref?money(ref):"—"}<small>{delta===null?"":(delta>0?"+":"")+delta.toFixed(0)+"%"}</small></td><td><div className="market-badges">{item.trustBadges.slice(0,3).map(b=><span key={b.label} data-tone={b.tone} title={b.detail}>{b.label}</span>)}</div></td><td>{new Date(item.updatedAt).toLocaleDateString("tr-TR")}</td><td><FavoriteButton item={item}/></td></tr>}
