"use client";
import {useEffect,useState} from "react";
import {memberCall} from "./uretir-id-shell";
import type {MemberContent} from "@/lib/members/types";
export function MemberReview(){const[items,setItems]=useState<MemberContent[]>([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[notes,setNotes]=useState<Record<string,string>>({});
 async function load(){const r=await fetch("/api/members?view=review",{cache:"no-store"});if(!r.ok)throw Error("İnceleme listesine erişilemedi.");setItems((await r.json()).items);}
 useEffect(()=>{load().catch(e=>setMessage(e.message));},[]);
 async function review(item:MemberContent,decision:string){setBusy(true);try{await memberCall({action:"review",id:item.id,version:item.version,decision,note:notes[item.id]??""});await load();setMessage("İçerik durumu güncellendi.");}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 return <section className="member-review"><h2>Üretir ID · Yayın incelemesi</h2><p>Başlık, metin, şehir ve bağlantıyı inceleyin. Girişim yayını şirketin veya finansal değerlerinin doğrulandığı anlamına gelmez.</p><button disabled={busy} onClick={()=>load().catch(e=>setMessage(e.message))}>Listeyi yenile</button><p role="status">{message}</p>{!items.length&&<p>Bekleyen veya yayımlanmış üye içeriği yok.</p>}{items.map(i=><article key={i.id}><small>{i.kind==="startup"?"Girişim":i.kind==="post"?"Yazı":"Yorum"} · {i.status==="pending"?"İncelemede":"Yayında"} · @{i.handle}</small><h3>{i.payload.title??i.payload.name??"Yorum"}</h3><p className="member-prose">{i.payload.description??i.payload.body}</p>{i.payload.product&&<p>{i.payload.product} · İl: {i.payload.cityCode} · {i.payload.stage}</p>}{i.payload.website&&<a target="_blank" rel="noreferrer" href={i.payload.website}>Beyan edilen siteyi aç ↗</a>}<label className="member-field"><span>İnceleme notu</span><input maxLength={500} value={notes[i.id]??""} onChange={e=>setNotes({...notes,[i.id]:e.target.value})}/></label><div className="member-buttons">{i.status==="pending"&&<button disabled={busy} onClick={()=>void review(i,"published")}>Onayla ve yayımla</button>}<button disabled={busy} onClick={()=>void review(i,"rejected")}>{i.status==="published"?"Yayından kaldır":"Düzenleme iste"}</button></div></article>)}</section>;
}
