"use client";
import {useState} from "react";
import Link from "next/link";
import provinces from "@/lib/haber-ai/provinces.json";
import map from "@/lib/haber-ai/map.json";
import type {StartupEntry} from "@/lib/startup-directory";
export function StartupDirectory({mode,startupEntries,initialCity=""}:{mode:"harita"|"marketplace"|"marketcap";startupEntries:StartupEntry[];initialCity?:string}){
 const[city,setCity]=useState(initialCity),[query,setQuery]=useState("");
 const entries=startupEntries.filter(e=>(!city||e.cityCode===city)&&(!query||(e.name+" "+e.product).toLocaleLowerCase("tr-TR").includes(query.toLocaleLowerCase("tr-TR"))));
 const title={harita:"Girişim haritası",marketplace:"Marketplace",marketcap:"Marketcap"}[mode];
 return <div className="section-wrap category-hub"><Link href="/ekosistem">← Ekosistem</Link><header><p className="rule-label">EKOSİSTEM / BAĞIMSIZ GİRİŞİMLER</p><h1>{title}<span>.</span></h1><p>{mode==="harita"?"Türkiye genelindeki girişimleri şehirlerinden keşfedin.":mode==="marketplace"?"Bağımsız girişimlerin ürün ve hizmetleri için keşif kataloğu.":"Girişimlerin kamuya açık finansal bilgileri ve risk görünümü."}</p></header><nav className="directory-tabs" aria-label="Ekosistem bölümleri">{["harita","marketplace","marketcap"].map(m=><Link aria-current={mode===m?"page":undefined} href={"/ekosistem/"+m} key={m}>{m==="harita"?"Harita":m==="marketplace"?"Marketplace":"Marketcap"}</Link>)}</nav><p><Link className="member-primary" href="/uretir-id">Girişimini haritaya ekle ↗</Link></p><div className="directory-filters"><label>Şehir<select value={city} onChange={e=>setCity(e.target.value)}><option value="">Tüm Türkiye</option>{provinces.map(p=><option value={p.code} key={p.code}>{p.name}</option>)}</select></label><label>Girişim veya ürün ara<input value={query} onChange={e=>setQuery(e.target.value)}/></label></div>
 {mode==="harita"&&<div className="directory-map"><svg viewBox="0 0 1007.478 527.323" aria-label="Türkiye girişim haritası">{map.map(p=><g key={p.code} role="button" tabIndex={0} aria-label={p.name} aria-pressed={city===p.code} className={(city===p.code?"selected ":"")+(startupEntries.some(e=>e.cityCode===p.code)?"has-entry":"")} onClick={()=>setCity(city===p.code?"":p.code)} onKeyDown={e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();setCity(city===p.code?"":p.code);}}}><title>{p.name}</title>{p.paths.map((d,i)=><path d={d} key={i}/>)}</g>)}</svg></div>}
 <div aria-live="polite" className="directory-result"><h2>{provinces.find(p=>p.code===city)?.name??"Türkiye"} · {entries.length} girişim</h2>{entries.length?entries.map(e=><article key={e.id}><h3><Link href={"/ekosistem/girisim/"+e.id}>{e.name} ↗</Link></h3><p>{e.description}</p><p>{e.product}</p>{mode==="marketcap"&&(e.publicFinancials?<div><p>Piyasa değeri: {e.publicFinancials.marketCapTRY.toLocaleString("tr-TR")} TL · {e.publicFinancials.asOf}</p><a href={e.publicFinancials.sourceUrl} target="_blank" rel="noreferrer">Finansal kaynak ↗</a><ul>{e.publicFinancials.risks.map(r=><li key={r}>{r}</li>)}</ul></div>:<p>Doğrulanmış, kamuya açık finansal veri yok.</p>)}<Link href={"/ekosistem/girisim/"+e.id}>Profil ve yazılar →</Link></article>):<p>Bu seçimde yayımlanmış girişim kaydı bulunmuyor. Girişiminizi paylaşmak için <Link href="/uretir-id">Üretir ID ile giriş yapın</Link>.</p>}</div>
 <aside className="category-note">{mode==="marketcap"?"Piyasa değeri, özel şirket değerlemesi ve halka açıklık oranı farklı bilgilerdir. Yalnızca kaynağı ve tarihi doğrulanmış veriler yayımlanır. Finansal bilgi bulunmaması düşük risk anlamına gelmez; veri yoksa değer veya risk puanı üretilmez.":mode==="marketplace"?"Bu bölüm ürün keşfi için hazırlanmıştır. Henüz satış, ödeme veya sipariş altyapısı sunulmuyor.":"Girişimler kurucu beyanıyla ve yayın incelemesi sonrası listelenir. Harita 81 ili kapsar. Bir şehirde kayıt bulunmaması, o şehirde girişim olmadığı anlamına gelmez."}</aside></div>;
}
