import Link from "next/link";
import { ApplicationsDirectory } from "@/components/applications-directory";
const tools = [
  { name: "UretirAI", description: "Üretim sorularını kaynaklar ve bağlantılı varlıklarla araştırın.", href: "/uretir-ai", color: "#78a5b6", status: "Bilgi temeli" },
  { name: "PuanAI", description: "Doğrulanmış kampanyalarla açıklanabilir alışveriş karar akışını kullanın.", href: "/puan-ai", color: "#c8f560", status: "Kullanıma açık" },
  { name: "OyunAI", description: "Memo ile İngilizce kelimeleri görselleriyle eşleştirerek hafızanızı geliştirin.", href: "/oyun-ai", color: "#4f46e5", status: "Kullanıma açık" },
  { name: "TeşvikAI", description: "Teşvik hazırlığını resmî kaynaklar ve kontrol listeleriyle yönetin.", href: "/tesvik-ai", color: "#8b80c2", status: "Bilgi temeli" },
  { name: "FiyatAI", description: "Hammadde tekliflerini ve fiyat serilerini doğru karşılaştırmayı öğrenin.", href: "/fiyat-ai", color: "#d97835", status: "Entegrasyon gelecek" },
  { name: "İhracatAI", description: "İhracat hazırlığını ve resmî destek kaynaklarını tek rotada inceleyin.", href: "/ihracat-ai", color: "#b26959", status: "Bilgi temeli" },
  { name: "İnsanAI", description: "Üreten insanların katkılarını güvenilir kaynaklar ve ilişkilerle araştırın.", href: "/insan-ai", color: "#78a5b6", status: "Bilgi temeli" },
  { name: "MimarAI", description: "Mekân ihtiyacını uygulanabilir ve doğrulanabilir bir tasarım özetine dönüştürün.", href: "/mimar-ai", color: "#78a5b6", status: "Hazırlanıyor" },
  { name: "İndirimAI", description: "İndirimleri koşullar ve gerçek toplam maliyet üzerinden karşılaştırın.", href: "/indirim-ai", color: "#d97835", status: "Hazırlanıyor" },
  { name: "MagazinAI", description: "Kültür ve gündemi söylentiden ayırarak kaynaklarıyla izleyin.", href: "/magazin-ai", color: "#b15c89", status: "Hazırlanıyor" },
  { name: "Trend Merkezi", description: "Doğrulanmış arama ve sektör sinyallerinden içerik fırsatları üretin.", href: "/trendler", color: "#d97835", status: "Kaynak bekliyor" },
];

const descriptions=["Research manufacturing questions with sources and related concepts.","Explore verified shopping campaigns and their conditions.","Match English words with pictures in the Memo memory game.","Prepare for incentives with official sources and checklists.","Learn to compare raw material quotes and price series.","Explore export readiness and official support resources.","Research makers and their contributions through credible sources.","Turn spatial requirements into a design brief.","Compare discounts using conditions and total costs.","Follow culture and news with traceable sources.","Explore verified search and industry signals."];
const statuses:Record<string,string>={"Bilgi temeli":"Guides","Kullanıma açık":"Available","Entegrasyon gelecek":"Integration planned","Hazırlanıyor":"In preparation","Kaynak bekliyor":"Awaiting sources"};
export function ToolsDirectory({english=false}:{english?:boolean}){return <div className="section-wrap py-12 md:py-20"><header className="mb-12 max-w-3xl"><h1 className="font-display text-5xl md:text-7xl">{english?"Tools":"Araçlar"}</h1><p className="mt-6 text-lg leading-8 text-muted">{english?"Web products for everyday work, plus Uretir’s AI tools and research guides.":"İşini kolaylaştıran web ürünleri, Üretir’in yapay zekâ araçları ve araştırma rehberleri."}</p></header><section><h2 className="mb-8 font-display text-3xl">{english?"Web products":"Web ürünleri"}</h2><ApplicationsDirectory platform="WEB" english={english}/></section><section className="mt-16"><h2 className="mb-4 font-display text-3xl">{english?"Uretir tools":"Üretir araçları"}</h2><p className="mb-8 text-base leading-7 text-muted">{english?"Availability is shown on each card. Tools in preparation are not yet open for use.":"Her kartta aracın güncel durumunu görebilirsin. Hazırlanan araçlar henüz kullanıma açık değil."}</p><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{tools.map((tool,i)=><article key={tool.href} className="flex flex-col border hairline p-6"><span className="self-start rounded-full border hairline px-3 py-1 text-sm">{english?statuses[tool.status]:tool.status}</span><h3 className="mt-7 font-display text-3xl">{tool.name}</h3><p className="mt-4 flex-1 text-base leading-7 text-muted">{english?descriptions[i]:tool.description}</p>{english?<a className="mt-6 text-sm underline" href={"https://translate.google.com/translate?sl=tr&tl=en&u="+encodeURIComponent("https://www.uretir.com"+tool.href)}>Read with Google Translate ↗</a>:<Link className="mt-6 text-sm underline" href={tool.href}>{tool.status==="Kullanıma açık"?"Aracı aç":"İncele"} ↗</Link>}</article>)}</div></section></div>}
