"use client";
import {useEffect,useState,FormEvent} from "react";
import Link from "next/link";
import provinces from "@/lib/haber-ai/provinces.json";
import type {Member,MemberContent,ContentKind,ContentPayload} from "@/lib/members/types";
export async function memberCall(data:unknown){const r=await fetch("/api/members",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const d=await r.json();if(!r.ok)throw Error(d.error??"İşlem tamamlanamadı.");return d;}
const statuses={draft:"Taslak",pending:"İncelemede",published:"Yayında",rejected:"Düzenleme gerekli"};
function Field({label,value,onChange,area=false,max=2000}:{label:string;value:string;onChange:(v:string)=>void;area?:boolean;max?:number}){return <label className="member-field"><span>{label}</span>{area?<textarea required rows={6} maxLength={max} value={value} onChange={e=>onChange(e.target.value)}/>:<input required maxLength={max} value={value} onChange={e=>onChange(e.target.value)}/>}</label>;}
function ContentForm({kind,item,startupId,onSaved}:{kind:ContentKind;item?:MemberContent;startupId?:string;onSaved:(id:string)=>Promise<void>}){
 const[p,setP]=useState<ContentPayload>(item?.payload??(kind==="startup"?{name:"",cityCode:"",product:"",description:"",website:"",stage:"Fikir"}:{title:"",body:"",topic:"Ürün fikri"}));const[busy,setBusy]=useState(false),[error,setError]=useState("");
 const change=(key:string,value:string)=>setP({...p,[key]:value});
 async function save(submit:boolean){setBusy(true);setError("");try{const d=await memberCall({action:"save",id:item?.id,kind,version:item?.version,parentId:kind==="post"?(item?.parent_id??startupId??null):null,payload:p,submit});await onSaved(d.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <form className="member-form" onSubmit={e=>{e.preventDefault();void save(true);}}><div className="member-form-head"><h2>{kind==="startup"?"Girişimini tanıt":"Fikrini yazıya dönüştür"}</h2><span>{item?statuses[item.status]:"Yeni taslak"}</span></div>
 {kind==="startup"?<><Field label="Girişim adı" value={p.name??""} max={100} onChange={v=>change("name",v)}/><div className="member-two"><label className="member-field"><span>Şehir</span><select required value={p.cityCode??""} onChange={e=>change("cityCode",e.target.value)}><option value="">Şehrini seç</option>{provinces.map(c=><option key={c.code} value={c.code}>{c.name}</option>)}</select></label><label className="member-field"><span>Aşama</span><select value={p.stage} onChange={e=>change("stage",e.target.value)}>{["Fikir","Prototip","Kullanımda"].map(v=><option key={v}>{v}</option>)}</select></label></div><Field label="Ne üretiyorsun? Tek cümleyle anlat." value={p.product??""} max={160} onChange={v=>change("product",v)}/><Field label="Hangi sorunu, kim için çözüyorsun? (En az 30 karakter)" value={p.description??""} area onChange={v=>change("description",v)}/><label className="member-field"><span>Web sitesi (isteğe bağlı, https://)</span><input type="url" maxLength={300} value={p.website??""} onChange={e=>change("website",e.target.value)}/></label></>:<><Field label="Yazı başlığı" value={p.title??""} max={140} onChange={v=>change("title",v)}/><label className="member-field"><span>Konu</span><select value={p.topic} onChange={e=>change("topic",e.target.value)}>{["Ürün fikri","Geliştirme günlüğü","Geri bildirim","Girişimcilik"].map(t=><option key={t}>{t}</option>)}</select></label><Field label="Fikrini anlat, deneyimini paylaş veya topluluğa bir soru sor. (En az 60 karakter)" value={p.body??""} max={12000} area onChange={v=>change("body",v)}/><p className="member-help">{startupId?"Yazın girişim profilinle ilişkilendirilir.":"Yazın profilinle yayımlanır. İstersen önce girişimini ekleyebilirsin."}</p></>}
 {item?.review_note&&<p className="member-notice">Editör notu: {item.review_note}</p>}<p className="member-help">Yayımlanan içerik düzenlenince yeniden taslak olur ve onaylanana kadar görünmez. Metinler düz yazı olarak yayımlanır.</p>{error&&<p role="alert">{error}</p>}<div className="member-buttons"><button type="button" disabled={busy} onClick={()=>void save(false)}>Taslak kaydet</button><button className="member-primary" disabled={busy} type="submit">{busy?"Kaydediliyor…":"İncelemeye gönder →"}</button></div></form>;
}
export function UretirIdShell(){
 const[user,setUser]=useState<Member|null>(null),[items,setItems]=useState<MemberContent[]>([]),[loading,setLoading]=useState(true),[mode,setMode]=useState("login"),[tab,setTab]=useState("overview"),[selected,setSelected]=useState<string|null>(null),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[recovery,setRecovery]=useState("");
 async function load(){const r=await fetch("/api/members",{cache:"no-store"});if(!r.ok)throw Error("Hesaba ulaşılamadı. Yenileyip tekrar deneyin.");const d=await r.json();setUser(d.user);setItems(d.items);return d;}
 useEffect(()=>{load().catch(e=>setMessage(e.message)).finally(()=>setLoading(false));},[]);
 const startup=items.find(i=>i.kind==="startup"),posts=items.filter(i=>i.kind==="post"),comments=items.filter(i=>i.kind==="comment");
 async function auth(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setMessage("");try{const f=new FormData(e.currentTarget);const d=await memberCall({action:mode,handle:f.get("handle"),password:f.get("password"),displayName:f.get("displayName"),recoveryCode:f.get("recoveryCode"),consent:f.get("consent")==="on"});if(d.recoveryCode)setRecovery(d.recoveryCode);await load();if(mode==="recover"){setMode("login");setMessage("Şifre yenilendi. Yeni kurtarma kodunu saklayıp giriş yap.");}}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function saved(id:string){await load();setSelected(id);setMessage("Kaydedildi. Durumunu çalışma alanından takip edebilirsin.");}
 const recoveryNotice=recovery&&<aside className="member-recovery" role="status"><strong>Hesap kurtarma kodun — yalnızca şimdi gösterilir</strong><p>Bu kodu güvenli bir yerde sakla. E-posta ile kurtarma yoktur; şifreni unuttuğunda bu kod gerekir.</p><code>{recovery}</code><button onClick={()=>setRecovery("")}>Kodu güvenli yere kaydettim</button></aside>;
 if(loading)return <div className="section-wrap member-shell"><p role="status">Çalışma alanın yükleniyor…</p></div>;
 if(!user)return <div className="section-wrap member-shell">{recoveryNotice}<div className="member-entry"><div><span className="rule-label">ÜRETİR ID / ÜRETENLER İÇİN</span><h1>Girişiminin<br/><em>bir yeri olsun.</em></h1><p>Girişimini tanıt. Haritada yerini al.<br/>Yazılarınla fikrini aç, topluluktan geri bildirim al.</p><ol className="member-steps"><li><b>01</b><span>Profilini oluştur<small>İnsanlar ne ürettiğini ve kimin için ürettiğini görsün.</small></span></li><li><b>02</b><span>Şehrinde görünür ol<small>Onaylanan girişimin harita ve katalogda yer alsın.</small></span></li><li><b>03</b><span>Fikrini tartışmaya aç<small>Bir gelişme paylaş, anlamlı sorularla ilerle.</small></span></li></ol></div><section className="member-auth"><div className="member-tabs"><button aria-pressed={mode==="login"} onClick={()=>setMode("login")}>Giriş yap</button><button aria-pressed={mode==="register"} onClick={()=>setMode("register")}>Hesap oluştur</button></div><h2>{mode==="register"?"Üretmeye katıl.":mode==="recover"?"Hesabını kurtar.":"Kaldığın yerden."}</h2><form onSubmit={auth}><label className="member-field"><span>Kullanıcı adı</span><input name="handle" required pattern="[a-z0-9_]{3,24}" minLength={3} maxLength={24} autoComplete="username" placeholder="ornek_girisim"/></label>{mode==="register"&&<label className="member-field"><span>Görünen adın</span><input name="displayName" required minLength={2} maxLength={60} autoComplete="name"/></label>}{mode==="recover"&&<label className="member-field"><span>Kurtarma kodu</span><input name="recoveryCode" required minLength={48} maxLength={48}/></label>}<label className="member-field"><span>{mode==="recover"?"Yeni şifre":"Şifre"} · en az 12 karakter</span><input name="password" type="password" required minLength={12} maxLength={128} autoComplete={mode==="login"?"current-password":"new-password"}/></label>{mode==="register"&&<label className="member-consent"><input required type="checkbox" name="consent"/><span><Link href="/gizlilik-politikasi">Gizlilik bilgilendirmesini</Link> okudum. Gönderdiğim içeriği yayımlama hakkına sahibim; paylaşımlar inceleme sonrasında herkese açık olur.</span></label>}<button className="member-primary" disabled={busy}>{busy?"İşleniyor…":mode==="register"?"Hesabımı oluştur →":mode==="recover"?"Şifreyi yenile":"Çalışma alanıma gir →"}</button></form><button className="member-text-button" onClick={()=>setMode(mode==="recover"?"login":"recover")}>{mode==="recover"?"Girişe dön":"Şifremi unuttum"}</button>{message&&<p role="status">{message}</p>}<p className="member-help">Hesap girişinde kullanıcı adı kullanılır. Yazılar, girişim bilgileri ve görünen adın yayımlandığında herkese açıktır.</p></section></div></div>;
 return <div className="section-wrap member-shell">{recoveryNotice}<header className="member-dashboard-head"><div><span className="rule-label">ÜRETİR ID / ÇALIŞMA ALANI</span><h1>Merhaba, {user.display_name}.</h1><p>Bugün fikrini bir adım ileri taşı.</p></div><button onClick={async()=>{try{await memberCall({action:"logout"});setUser(null);setItems([]);setRecovery("");}catch(e){setMessage((e as Error).message);}}}>Çıkış yap</button></header><nav className="member-tabs" aria-label="Çalışma alanı">{[["overview","Genel bakış"],["startup","Girişimim"],["posts","Yazılarım"],["account","Hesabım"]].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>{setTab(id);setMessage("");}}>{label}</button>)}</nav>{message&&<p className="member-notice" role="status">{message}</p>}
 {tab==="overview"&&<><div className="member-overview"><button onClick={()=>setTab("startup")}><small>HARİTADAKİ YERİN</small><strong>{startup?statuses[startup.status]:"İlk adımı at"}</strong><span>{startup?.payload.name??"Girişim profilini oluştur"} →</span></button><button onClick={()=>setTab("posts")}><small>YAZILARIN</small><strong>{posts.filter(p=>p.status==="published").length} yayında</strong><span>Fikrini güçlendir →</span></button><Link href="/kaynaklar/topluluk"><small>TOPLULUK</small><strong>Birlikte düşün</strong><span>Gündemdeki tartışmalara katıl →</span></Link></div><div className="member-next"><h2>{!startup?"Önce girişiminden bahset.":startup.status!=="published"?"Girişimini yayına hazırla.":"Şimdi hikâyeni paylaş."}</h2><p>{!startup?"Bir isim, bir şehir ve çözdüğün sorun yeterli. Başlamak için bir şirket kurmuş olman gerekmez.":"Taslaklarını tamamla; yayımlanan profilini yazılar ve topluluk geri bildirimleriyle geliştir."}</p><div className="member-buttons"><button className="member-primary" onClick={()=>setTab(!startup?"startup":"posts")}>{!startup?"Girişimimi ekle":"Yazı ekle"} →</button>{startup?.status==="published"&&<Link href={"/ekosistem/girisim/"+startup.id}>Girişim profilini gör ↗</Link>}</div></div>{comments.length>0&&<section className="member-next"><h2>Yorumların</h2>{comments.map(c=><p key={c.id}>{statuses[c.status]} · {c.payload.body?.slice(0,120)} {c.review_note&&"— "+c.review_note}</p>)}</section>}</>}
 {tab==="startup"&&<ContentForm key={startup?.version??"new-startup"} kind="startup" item={startup} onSaved={saved}/>}
 {tab==="posts"&&<div className="member-writing"><aside><button className="member-primary" onClick={()=>setSelected(null)}>+ Yeni yazı</button>{posts.map(p=><button className="member-post-choice" key={p.id} onClick={()=>setSelected(p.id)}><strong>{p.payload.title}</strong><small>{statuses[p.status]}</small></button>)}</aside><ContentForm key={(selected??"new")+":"+(posts.find(p=>p.id===selected)?.version??0)} kind="post" item={posts.find(p=>p.id===selected)} startupId={startup?.id} onSaved={saved}/></div>}
 {tab==="account"&&<div className="member-form"><h2>Hesap ve içerik kontrolü</h2><p>@{user.handle}</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await memberCall({action:"profile",displayName:f.get("displayName")});await load();setMessage("Görünen ad güncellendi.");}catch(e){setMessage((e as Error).message);}}}><label className="member-field"><span>Görünen ad</span><input name="displayName" defaultValue={user.display_name} required minLength={2} maxLength={60}/></label><button>Adı kaydet</button></form><h3>İçeriğini kaldır</h3><p className="member-help">Kaldırılan yazının altındaki yorumlar da silinir.</p>{items.filter(i=>i.kind!=="comment").map(i=><p key={i.id}>{i.payload.title??i.payload.name} <button onClick={async()=>{if(!window.confirm("Bu içerik ve bağlı içerikler kalıcı olarak silinsin mi?"))return;try{await memberCall({action:"delete",id:i.id});await load();setMessage("İçerik silindi.");}catch(e){setMessage((e as Error).message);}}}>Sil</button></p>)}<hr/><h3>Hesabı kalıcı olarak sil</h3><p>Profilin, girişimin, yazıların ve yorumların kaldırılır. Geri alınamaz.</p><form onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(!window.confirm("Hesabını ve tüm içeriklerini kalıcı olarak silmek istediğine emin misin?"))return;try{await memberCall({action:"deleteAccount",password:f.get("password")});setUser(null);setItems([]);setMessage("Hesabın silindi.");}catch(e){setMessage((e as Error).message);}}}><label className="member-field"><span>Onaylamak için mevcut şifren</span><input type="password" name="password" autoComplete="current-password" required/></label><button>Hesabımı ve içeriklerimi sil</button></form></div>}</div>;
}
