import {getPrisma} from "@/lib/puan-ai/db";
const DAY=86400000,clamp=(n:number,min=0,max=1)=>Math.max(min,Math.min(max,n)),median=(a:number[])=>{const v=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!v.length)return null;const m=Math.floor(v.length/2);return v.length%2?v[m]:(v[m-1]+v[m])/2;};
export type EvCandidate={listingKey:string;sourceId:string;sourceName:string;sourceKind:string;listingType:string;propertyType:string;title:string;city:string|null;district:string|null;rooms:string|null;grossM2:number|null;price:number|null;pricePerM2:number|null;isPublicAuction:boolean;sourceUrl:string;imageUrl:string|null;publishedAt:string|null;fetchedAt:string;score:number;localMedianPerM2:number|null;valueDeltaPct:number|null;priceDropPct:number|null;reasons:string[]};
export async function getEvAIReport(now=new Date()){
 const prisma=getPrisma(),rows=await prisma.propertyListingObservation.findMany({where:{fetchedAt:{gte:new Date(now.getTime()-30*DAY)}},orderBy:{fetchedAt:"desc"},take:30000}),hist=new Map<string,typeof rows>();
 for(const r of rows){const a=hist.get(r.listingKey)??[];a.push(r);hist.set(r.listingKey,a);}
 const latest=[...hist.values()].map(h=>h[0]).filter(r=>now.getTime()-r.fetchedAt.getTime()<=(r.isPublicAuction?21*DAY:4*DAY)),local=new Map<string,number[]>(),citywide=new Map<string,number[]>();
 for(const r of latest){const p=r.pricePerM2?.toNumber();if(!p||r.isPublicAuction)continue;const k=[r.city??"",r.district??"",r.listingType,r.propertyType].join("|"),c=[r.city??"",r.listingType,r.propertyType].join("|"),a=local.get(k)??[],b=citywide.get(c)??[];a.push(p);b.push(p);local.set(k,a);citywide.set(c,b);}
 const cand:EvCandidate[]=[];
 for(const r of latest){const h=hist.get(r.listingKey)??[r],prev=h.find(x=>x.fingerprint!==r.fingerprint&&x.price!==null),price=r.price?.toNumber()??null,ppm=r.pricePerM2?.toNumber()??null,gross=r.grossM2?.toNumber()??null,prevPrice=prev?.price?.toNumber()??null,drop=price&&prevPrice&&prevPrice>price?(prevPrice-price)/prevPrice*100:null,k=[r.city??"",r.district??"",r.listingType,r.propertyType].join("|"),c=[r.city??"",r.listingType,r.propertyType].join("|"),lv=local.get(k)??[],cv=citywide.get(c)??[],med=median(lv.length>=5?lv:cv.length>=8?cv:[]),delta=ppm&&med?(med-ppm)/med*100:null,age=(now.getTime()-r.fetchedAt.getTime())/3600000;
  const score=Math.round(clamp(r.trustScore/100*20+(1-clamp(age/(r.isPublicAuction?504:96)))*20+[r.city,r.district,gross,r.rooms,price].filter(Boolean).length/5*15+(r.isPublicAuction?0:clamp((delta??0)/25)*35)+clamp((drop??0)/15)*10+(r.isPublicAuction?20:0),0,100)),reasons:string[]=[];
  if(delta!==null&&delta>=5)reasons.push("Yerel m² medyanının %"+delta.toFixed(1)+" altında");if(drop!==null&&drop>=1)reasons.push("Fiyat önceki gözleme göre %"+drop.toFixed(1)+" düştü");if(r.isPublicAuction)reasons.push("Kamu/icra kaynağında güncel taşınmaz ilanı");if(age<=24)reasons.push("Son 24 saatte doğrulandı");if(!reasons.length)reasons.push("Güncel ve kaynaklı ilan");
  if(r.isPublicAuction||score>=55)cand.push({listingKey:r.listingKey,sourceId:r.sourceId,sourceName:r.sourceName,sourceKind:r.sourceKind,listingType:r.listingType,propertyType:r.propertyType,title:r.title,city:r.city,district:r.district,rooms:r.rooms,grossM2:gross,price,pricePerM2:ppm,isPublicAuction:r.isPublicAuction,sourceUrl:r.sourceUrl,imageUrl:r.imageUrl,publishedAt:r.publishedAt?.toISOString()??null,fetchedAt:r.fetchedAt.toISOString(),score,localMedianPerM2:med,valueDeltaPct:delta,priceDropPct:drop,reasons});}
 cand.sort((a,b)=>b.score-a.score||(b.valueDeltaPct??-999)-(a.valueDeltaPct??-999));const selected:EvCandidate[]=[],cc=new Map<string,number>(),sc=new Map<string,number>();for(const x of cand){const c=x.city??"Bilinmeyen";if((cc.get(c)??0)>=3||(sc.get(x.sourceId)??0)>=4)continue;selected.push(x);cc.set(c,(cc.get(c)??0)+1);sc.set(x.sourceId,(sc.get(x.sourceId)??0)+1);if(selected.length>=60)break;}return {checkedAt:now.toISOString(),candidateCount:selected.length,observations:rows.length,items:selected};
}
